### ISSUE TITLE
[Request] Release build in Appstore (or elsewhere)

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#1]
Hi! That's some impressive work you've done there. Didn't even know this existed for BlackBerry 10 and is progressing so nicely! Any chance you could release a build here, on Beta Zone or even BlackBerry World to make it more accessible? This kind of software is really missing on the platform. Thanks for your efforts anyway!

**Comment by Viish** [comment]
Hi,

Thanks for your comment.
Yes we'll publish it on the Blackberry World once the app will be finished. There is still some work to do.

Cheers.

**Comment by stmblfrcr** [comment]
Thanks! Good to hear.

**Comment by stmblfrcr** [comment]
Hi, me again. I see, you made great progress. Any chance for a release in the near future or a status update? Regards.

**Comment by Viish** [comment]
Hi,

I've pushed the Blackberry app for review a few hours ago.
Hopefully it will be on the AppWorld soon.

Cheers.

**Comment by stmblfrcr** [comment]
Haven't tried it yet, but it has just been promoted to BB World :). I can't thank you enough!

**Comment by Viish** [comment]
You're very welcome :)
