### ISSUE TITLE
Reduce size of deployed app

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#2]
Don't know, if you're open for some bug reports, but here I go anyway - the size of the app is around 70MB, which is rather high imho. Especially since almost half of it seems to be one file named dont_wait_too_long.wav. In fact, the big size is mostly due to several mega byte sized WAV-files. Is it really necessary to ship these with the application? It may look weird to end users and makes install/update processes time consuming, not everybody has fiber internet. Regards.

**Comment by Viish** [comment]
Thanks for pointing that out, I didn't noticed it. I'll fix it.

**Comment by Viish** [comment]
It is now fixed. A new release 1.0.1 is pending Blackberry approval.

**Comment by Viish** [comment]
1.0.1 release is now published.
