### ISSUE TITLE
Suboptimal OS Version in About Screen

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#3]
Just some really small gripe - in the about screen it states "BlackBerry OS 10.3.1.0" despite running a version of 10.3.2. I guess, that's the latest SDK version, but from an end users perspective it should make more sense to either print "SDK version" or print the actual OS version. Regards.

**Comment by Viish** [comment]
You're right, I'll fix that. Thanks.

**Comment by Viish** [comment]
It is now fixed. A new release 1.0.1 is pending Blackberry approval.

**Comment by Viish** [comment]
1.0.1 release is now published.
