### ISSUE TITLE
UI Improvements, Suggestions, ...

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#4]
While it seems, you already used some QML elements like switches and drop-down menus, the app still lacks native feel. It would be great, if you could apply some BlackBerry Cascades design principles like menus, swipe gestures, themes (people love the inverted theme) it would certainly help the app to stand out more. Furthermore, active frames could be used https://developer.blackberry.com/native/documentation/ui/index.html . Something like this helps marketing as well http://devblog.blackberry.com/2016/02/great-apps-on-blackberry/ . Regards.

**Comment by Viish** [comment]
We made the choice to have the same application UI on each platform (Android, iOS, Blackberry) to make the transition easy for the user between different devices with different OS, so we won't make any changes in that direction.
However nothing prevent you to fork the project and make your own UI.
