### ISSUE TITLE
Headless / Run in Background Functionality

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#5]
This is probably the hardest one to implement, but what really makes an application like VoIP shine is, when it runs in the background. While it is a tedious amount of work, this is one of the most prominent features on a multitasking OS like BlackBerry 10. People don't want to leave the app open all the time, for now, when the app is not active, it loses connection and has to re-register with the server again. More info: https://developer.blackberry.com/native/documentation/device_platform/headless_apps/ . Regards.

**Comment by Viish** [comment]
We know about that, but it is planned yet. Maybe one day we'll do it.
