### ISSUE TITLE
Registration from within application appears to be broken

### ISSUE THREAD

**Issue by stmblfrcr** [BelledonneCommunications/linphone-bb10#6]
First of all, thanks for your continued commitment. According to (negative) store reviews and this thread http://forums.crackberry.com/blackberry-10-apps-f274/linphone-new-voip-app-blackberry-10-a-1068225/ it doesn't seem to be possible, to register a new Linphone account from inside the app. I wasn't successful myself, but it worked on the website. Where are the log files stored? Is it possible to debug and paste them into the home folder? Thanks and regards!

**Comment by Viish** [comment]
Hi,

Thanks for sending us the link to the thread. I'll take a look at the wizard registration issue.
Regarding the logs, when you enable the debug mode is the settings, you have a upload log collection button that zip them and upload them on our sever. You can use the link to download it if you want.

Cheers.

**Comment by Viish** [comment]
It is now resolved, will be in 1.0.2.

**Comment by Viish** [comment]
Release 1.0.2 is available for download.
